#!/usr/bin/env node
// Push config/ into the database: niches, the scoring profile and campaigns.
//
//   node scripts/load-config.mjs --sql            print SQL (no network)
//   node scripts/load-config.mjs --apply          POST to Supabase using .env
//
// The JSON files stay the source of truth and stay diffable in git; this just
// mirrors them into the tables the workflows read at runtime.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));

// The schema mixes text[] and jsonb columns, so the caller says which is which
// rather than the serialiser guessing from the JavaScript value.
const TEXT_ARRAY_COLUMNS = new Set(['keywords', 'negative_keywords', 'search_terms', 'instagram_hashtags']);

const quote = (value, column = null) => {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value) && TEXT_ARRAY_COLUMNS.has(column)) {
    return `ARRAY[${value.map((v) => `'${String(v).replace(/'/g, "''")}'`).join(', ')}]::text[]`;
  }
  if (typeof value === 'object') return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  return `'${String(value).replace(/'/g, "''")}'`;
};

export function nicheSql(niche) {
  const columns = {
    id: niche.id,
    name: niche.name,
    tier: niche.tier ?? 'primary',
    business_model: niche.business_model ?? 'ecommerce_brand',
    keywords: niche.keywords ?? [],
    negative_keywords: niche.negative_keywords ?? [],
    search_terms: niche.search_terms ?? [],
    instagram_hashtags: niche.instagram_hashtags ?? [],
    default_locations: niche.default_locations ?? {},
    icp_rules: niche.icp_rules ?? {},
    pain_points: niche.pain_points ?? [],
    recommended_services: niche.recommended_services ?? [],
    outreach_angles: niche.outreach_angles ?? []
  };
  const keys = Object.keys(columns);
  return `insert into niches (${keys.join(', ')})\nvalues (${keys.map((k) => quote(columns[k], k)).join(', ')})\non conflict (id) do update set\n${keys.filter((k) => k !== 'id').map((k) => `  ${k} = excluded.${k}`).join(',\n')},\n  updated_at = now();`;
}

export function campaignSql(campaign) {
  const columns = {
    id: campaign.id,
    name: campaign.name,
    status: campaign.status ?? 'draft',
    niche_id: campaign.niche_id,
    scoring_profile_id: campaign.qualification?.scoring_profile ?? 'default',
    targeting: campaign.targeting ?? {},
    icp: campaign.icp ?? {},
    discovery: campaign.discovery ?? {},
    enrichment: campaign.enrichment ?? {},
    qualification: campaign.qualification ?? {},
    research: campaign.research ?? {},
    outreach: campaign.outreach ?? {},
    followups: campaign.followups ?? {},
    mirror: campaign.mirror ?? {},
    schedule: campaign.schedule ?? {}
  };
  const keys = Object.keys(columns);
  return `insert into campaigns (${keys.join(', ')})\nvalues (${keys.map((k) => quote(columns[k], k)).join(', ')})\non conflict (id) do update set\n${keys.filter((k) => k !== 'id').map((k) => `  ${k} = excluded.${k}`).join(',\n')},\n  updated_at = now();`;
}

export function scoringSql(profile) {
  return `insert into scoring_profiles (id, name, config)\nvalues ('default', 'OptiFlow default ICP scoring', ${quote(profile)})\non conflict (id) do update set config = excluded.config, updated_at = now();`;
}

export function buildSql() {
  const niches = read('config/niches.json').niches;
  const campaigns = readdirSync(join(ROOT, 'config/campaigns'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => read(join('config/campaigns', f)));

  return [
    '-- Generated by scripts/load-config.mjs - do not edit by hand.',
    '-- Regenerate after changing anything in config/.',
    'begin;',
    scoringSql(read('config/scoring.default.json')),
    ...niches.map(nicheSql),
    ...campaigns.map(campaignSql),
    'commit;',
    ''
  ].join('\n\n');
}

async function apply() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error('Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, or run with --sql and pipe the output into psql.');
    process.exit(1);
  }
  const headers = { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'resolution=merge-duplicates,return=minimal' };

  const niches = read('config/niches.json').niches.map((n) => ({
    id: n.id, name: n.name, tier: n.tier, business_model: n.business_model,
    keywords: n.keywords, negative_keywords: n.negative_keywords, search_terms: n.search_terms,
    instagram_hashtags: n.instagram_hashtags, default_locations: n.default_locations,
    icp_rules: n.icp_rules, pain_points: n.pain_points,
    recommended_services: n.recommended_services, outreach_angles: n.outreach_angles
  }));

  const campaigns = readdirSync(join(ROOT, 'config/campaigns'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => read(join('config/campaigns', f)))
    .map((c) => ({
      id: c.id, name: c.name, status: c.status, niche_id: c.niche_id,
      scoring_profile_id: c.qualification?.scoring_profile ?? 'default',
      targeting: c.targeting, icp: c.icp, discovery: c.discovery, enrichment: c.enrichment,
      qualification: c.qualification, research: c.research, outreach: c.outreach,
      followups: c.followups, mirror: c.mirror, schedule: c.schedule
    }));

  for (const [table, rows] of [['niches', niches], ['campaigns', campaigns]]) {
    const response = await fetch(`${url.replace(/\/+$/, '')}/rest/v1/${table}?on_conflict=id`, {
      method: 'POST', headers, body: JSON.stringify(rows)
    });
    if (!response.ok) {
      console.error(`${table}: HTTP ${response.status} ${await response.text()}`);
      process.exit(1);
    }
    console.log(`${table}: ${rows.length} row(s) upserted`);
  }
}

const mode = process.argv[2] ?? '--sql';
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  if (mode === '--apply') {
    await apply();
  } else {
    const sql = buildSql();
    const out = join(ROOT, 'db/seed/0002_config.generated.sql');
    writeFileSync(out, sql);
    console.log(sql);
    console.error(`\nAlso written to ${out.replace(ROOT + '/', '')}`);
  }
}
